### ISSUE TITLE
<LOW>User "uneasiness-time" while waiting for the final UI 

### ISSUE THREAD

**Issue by kimo** [PySheets/pysheets#116]
It was difficult to explain. And I recorded the screen. Had to do it on low-res to keep the size down. Please take a look.

https://github.com/user-attachments/assets/14f02d8c-a7a7-4b45-bf7d-b57ae1451c79

@laffra @sangramsingh-kss

**Comment by laffra** [comment]
This behavior is happening due to https://github.com/PySheets/pysheets/blob/main/src/static/views/spreadsheet.py#L648. Once the worker has finished loading, we proactively evaluate all the cell, to get the sheet back into a proper state. I turned this into a more lazy approach, so the sheets stays more stable when the worker is ready.
